project:
  type: website
  output-dir: docs

website:
  title: "nataliesite"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Data Viz
        menu: 
          - text: "Refugees"
            href: TidyTuesday1.qmd
          - text: "World Heritage Sites"
            href: TidyTuesday2.qmd
          - text: "Text Analysis"
            href: Project 2.qmd
          - text: "Permutation Test"
            href: permutationtest.qmd
      - text: Designs
        menu: 
          - text: "User-Centered Community Experience Design"
            href: HCDexperience.qmd
          - text: "2024 Hackathon Figma"
            href: 2024hackathon.qmd
          - text: "P-ai UX Wireframe"
            href: paiproject.qmd
          - text: "Pitch Competition Product Design"
            href: pitchcompetition.qmd
      - text: Research
        href: aestheticsresearch.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

