project:
  type: website
  output-dir: docs

website:
  title: "nataliesite"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Data Viz
        menu: 
          - text: "Tidy Tuesday 1"
            href: TidyTuesday1.qmd
          - text: "Tidy Tuesday 2"
            href: TidyTuesday2.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

