project:
  type: website
  output-dir: docs

website:
  title: "nat on the web"
  favicon: Vector 1.png
  navbar:
    logo: Vector 1.png
    left:
      - href: index.qmd
        text: Home
      - text: Data Viz
        menu: 
          - text: "Refugees"
            href: TidyTuesday1.qmd
          - text: "World Heritage Sites"
            href: TidyTuesday2.qmd
          - text: "Text Analysis"
            href: Project 2.qmd
          - text: "Permutation Test"
            href: permutationtest.qmd
          - text: "SQL"
            href: sql_audio.qmd
          - text: "Client Presentation"
            href: clientpresentation.qmd
      - text: Designs
        menu: 
          - text: "Duolingo Product Design"
            href: pitchcompetition.qmd
          - text: "User-Centered Community Experience Design"
            href: HCDexperience.qmd
          - text: "Campus Rideshare App Wireframe"
            href: Sparkathon24.qmd
          - text: "Alchohol Safety App Figma"
            href: 2024hackathon.qmd
          - text: "Alumni Connectivity Wireframe"
            href: paiproject.qmd
          
      - text: Research
        href: aestheticsresearch.qmd
      - text: About
        href: aboutme.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    
editor: visual

