---
title: "Campus Rideshare Design for 2024 Sparkathon"
description: |
  The 2024 Sparkaton was a five hour case challenge with one prompt: Waste On Campus. After conducting user interviews, we identifed a need for better access to cars. The current options of ZipCar, Uber, and Turo
  were either inaccessible, expensive, or sketchy for college-age students. There was a real desire for
  rideshare **within** the Claremont College community, and thus UTurn was born. 
author: Natalie Roston
date: November 3, 2024
format: html
execute:
  warning: false
  message: false
---

## The Product

U-Turn has two features that target the concept of Waste.

1.  The rental feature allows students to lend cars to other students for a highly discounted rate.
    -   This mitigates economic hardship for the driver while keeping car usage circular within the college community.
2.  The second feature is a carpool option, an innovative concept that allows for students to pay for a single seat in a car already going to that destination.
    -   This way, students can lower carbon emissions by sharing transportation. It is also an accessible and cheap option for someone who might not have a car or license.

## The Prototype

<iframe style="border: 1px solid rgba(0, 0, 0, 0.1);" width="800" height="450" src="https://embed.figma.com/proto/9CE6v5epwauEwyovqeH81s/Uturn-Sparkathon?node-id=3-40&amp;scaling=scale-down&amp;content-scaling=fixed&amp;page-id=0%3A1&amp;starting-point-node-id=3%3A40&amp;embed-host=share" allowfullscreen>

</iframe>

## My Role

As product manager and project lead, I oversaw the development of my team's product. I started with initial user interviews to identify pain points, assisted in the design, and strategized our market and financial approach.
